runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run Application
      run: npm start & echo "Waiting for application to start..." && node_modules/.bin/wait-on --timeout 60000 http://localhost:3000 && echo "Application started successfully!"
      shell: bash

    - name: Run Cypress
      run: npm run cypress:coverage
      shell: bash
