runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run Application
      run: npm start & node_modules/.bin/wait-on http://localhost:3000
      shell: bash

    - name: Run Cypress
      run: npm run cypress:coverage
      shell: bash
