runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Start app and wait for it to start
      run: npm start & sleep 120
      shell: bash

    - name: Run Cypress
      run: npm run cypress:test-coverage
      shell: bash
