runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Cypress run
      uses: cypress-io/github-action@v3
      with:
        browser: chrome
        start: npm run start-with-coverage
        wait-on: "http://localhost:3000"
