runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        headed: true
        start: npm start
        wait-on: "http://localhost:3000"
        wait-on-timeout: 300

    - name: Get Coverage
      run: npm run cypress:coverage-summary
      shell: bash
