name: Cypress tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to run tests"
        required: true
        default: "test"
        options:
          dev:
            description: "Run tests in dev environment"
          test:
            description: "Run tests in test environment"

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config: pageLoadTimeout=100000,baseUrl=${{ secrets.DEV_URL }}
