name: Run Cypress Tests

on:
  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Cypress Tests
        uses: ./.github/actions/cypress
