name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          CYPRESS_BASE_URL: https://localhost:3000
        run: npm start & npm run cypress:test-coverage --env baseUrl=$CYPRESS_BASE_URL
