name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to run tests against"
        required: true
        default: "dev"
        options:
          dev:
            description: "Development environment"
          test:
            description: "Test environment"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ matrix.environment == 'dev' && secrets.DEV_URL || secrets.TEST_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Start app
        run: npm start &
        # Wait for the app to start up
        # You may need to adjust the delay depending on how long it takes for your app to start up
        # The default is 30 seconds, but you can increase or decrease it as needed
        timeout: 60s
      - name: Run Cypress tests
        run: npm run cypress:run
