name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          APP_ENV: ${{ matrix.env }}
          BASE_URL: ${{ secrets.DEV_URL }}
        run: npm start & npm run cypress:test-coverage
