name: CI

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "dev"
        options:
          dev: "Dev"
          test: "Test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MY_URL: ${{ github.event.inputs.env == 'test' && secrets.TEST_URL || secrets.DEV_URL }}
        run: npm start & npm run cypress:test-coverage --env baseUrl=$MY_URL
