# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Cypress-Test:
    runs-on: ubuntu-latest
    name: cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print name
        run: echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION. My API_KEY is ${{secrets.WEB_APP_ENV}}"
        env:
          BUILD: "We are currently running the Build job"

      - name: Run tests
        uses: ./.github/actions/cypress
        env: # Or as an environment variable
          credentials: ${{ secrets.WEB_APP_ENV }}
